### ISSUE TITLE
Include unzipped copy in repo

### ISSUE THREAD

**Issue by pepasflo** [timothymiko/swift-networking-examples#2]
Thanks so much for writing this article!

Unfortunately, there is currently no good way to view your source code without downloading the zip file and opening it up in Xcode:
- The layout of your blog post allows only about 580px width to show your source code.  Scrolling back and forth to read every single line is a really bad UX.
- Using a zip file in github defeats my ability to use github's excellent source code viewer.

I'd imagine that changing the layout of your blog post is probably a big lift, but including an unzipped copy of your playground in your github repo is an easy win! 👍

Thanks! 😄

**Comment by ttl-tim** [comment]
Ah this was totally unintentional, I'll include an unzipped version!

**Comment by pepasflo** [comment]
👍
